version: 0.0
os: linux
files:
  - source: /
    destination: /root

hooks:
  AfterInstall:
    - location: ./docker-script.sh
      timeout: 300
      runas: root
      command: ./docker-script.sh
ApplicationStart:
    - location: ./check-health.sh
      timeout: 90
      runas: root
      command: ./check-health.sh
