version: 0.0
os: linux
files:
  - source: /
    destination: /opt/java-app
    overwrite: true

hooks:
  AfterInstall:
    - location: ./docker-script.sh
      timeout: 300
      runas: root
      command: ./docker-script.sh
