version: '3'

services:
  python_app:
    image: 406749516863.dkr.ecr.ap-south-1.amazonaws.com/fiatpe:latest
    ports:
      - "8000:8000"
    command: ["bash", "first-time.sh"]
    networks:
      - my_network


  java:
    image: 406749516863.dkr.ecr.ap-south-1.amazonaws.com/java:latest
    ports:
      - "9090:9090"
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: overlay
